#- name: Installing the Repo file
#  ansible.builtin.shell: dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
#  ansible.builtin.yum:
#    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
#    state: installed
#    disable_gpg_check: true

#- name: Install Redis Repos
#  ansible.builtin.yum:
#    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
#    state: installed
#    disable_gpg_check: true

- name: Enable the redis 6 Version
  ansible.builtin.shell: dnf module enable redis:6 -y

- name: Install redis
  ansible.builtin.dnf:
    name: redis
    state: installed

- name: Update redis Listen Address
  ansible.builtin.replace:
    path: "{{ item }}"
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  loop:
    - /etc/redis.conf
    - /etc/redis/redis.conf

- name: SystemD setup
  ansible.builtin.systemd_service:
    name: redis
    state: restarted
    enabled: true  
   

# echo -e "${color} Enable and Start the ${component} ${nocolor}"
# systemctl enable ${component} &>>${log_file}
# systemctl restart ${component} &>>${log_file}