- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: latest 

- name: Remove Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create a Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: uploading the content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Config the Roboshop file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: etc/nginx/default.d/roboshop.conf

- name: systemd setup
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    enabled: true

# echo -e "${color} systemd start ${nocolor}"
# systemctl enable nginx &>>${log_file}
# systemctl restart nginx &>>${log_file}
# stat_check $?