- name: Disable the Mysql
  ansible.builtin.shell: dnf module disable mysql -y 

- name: Config the Roboshop file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install the MySQL Servier
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: systemd setup
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: true

- name: Setup the password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1
