# component=catalogue

# nodejs
# mongo_schema_setup


- name: nodejs setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

# - name: mongo schema setup
#   ansible.builtin.import_role:
#     name: common
#     tasks_from: mongo_schema_setup