
- name: Creating the Services
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo 

- name: Install mongodb
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: Loading the catalouge
  ansible.builtin.shell: mongo --host mongodb-{{env}}.erobo.online </app/schema/{{ component }}.js