
#     echo -e "${color} install mongodb ${nocolor}"
#     yum install mongodb-org-shell -y &>>${log_file}
#     stat_check $? 

#     echo -e "${color}  Loading the catalouge ${nocolor}"
#     mongo --host mongodb-dev.erobo.online <${app_path}/schema/${component}.js &>>${log_file}
#     stat_check $? 

- name: Creating the Services
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo 

- name: Install mongodb
  ansible.builtin.yum
    name: mongodb-org-shell
    state: installed

- name: Loading the catalouge
  ansible.builtin.shell: mongo --host mongodb-dev.erobo.online </app/schema/{{ component }}.js