

- name: Install MySQl
  ansible.builtin.shell: dnf install mysql -y 

- name: Load Schema
  ansible.builtin.shell: mysql -h mysql-{{env}}.erobo.online -uroot -pRoboShop@1 < /app/schema/shipping.sql 

