- name: Install Python
  ansible.builtin.yum:
    name: 
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Include task list in play
  ansible.builtin.import_tasks:
    file: app_presetup.yml

- name: Install Python pipe3.6
  ansible.builtin.shell: pip3.6 install -r requirements.txt
    chdir: /app

- name: Sysyemd setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml
