
- name: Creating the Services
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/{{ component }}.service  

- name: SystemD setup
  ansible.builtin.systemd_service:
    name: "{{ component }}"
    state: restarted
    enabled: true  
    daemon-reload: true

    